### ISSUE TITLE
Reword "Vis kun tilgjengelige arrangementer"

### ISSUE THREAD

**Issue by sklirg** [dotkom/onlineweb-frontend#118]
Since this is a 100% Norwegian issue I'll discuss it in Norwegian.

---

Hva betyr et "tilgjengelig" arrangement? For å være pedantisk kan man si at det er et arrangement som alle kan delta på (med tanke på tilgjengelighet, rullestolbrukere, svaksynte osv. osv.), eller så kunne det vært publiserte arrangementer, men i hvilket tilfelle ville vi vist arrangementer som da ikke er tilgjengelige? Med andre ord så syns jeg dagens beskrivelse er litt forvirrende/uklar.

Jeg ville brukt en beskrivende tekst som "Vis kun arrangementer jeg kan delta på" istedenfor og heller prøvd å ha en kort og en lang beskrivelse slik at det ikke tar så mye plass "til vanlig". Et beskrivende ikon kunne også vært den "korte" beskrivelsen, som gjør at ikonet kan ha en "av/på state" med en visuell indikator (som toggle-bryteren i dag, eller ikonet med en strek over). Se f.eks. "personalization"-ikoner.

Dette er selvfølgelig bare noe jeg har reagert på, så det kan være det bare er jeg som er i overkant vanskelig. :p

**Comment by oleast** [comment]
Jeg er veldig enig i det du sier, men jeg sliter litt med å finne ut hva vi faktisk skal putte der. Grunnen til at det er som i dag var at jeg fant det vanskelig å finne noe bedre på kort tid.

Synes det er litt problematisk at teksten er så lang, men det er kanskje også litt vanskelig å beskrive hva som gjøres med færre ord? Kan jo bruke noe som 'kan delta', men det høres litt rart ut.

Kan prøve noe som:
- [ ] _kan delta_

Hvor den legger til en liten linje med følgende tekst under når den er aktivert:
- [x] _kan delta_
_Viser kun arrangementer du kan delta på_

**Comment by mariush2** [comment]
Foreslår å bytte til "Vis arrangement du kan delta på".
