### ISSUE TITLE
Hover over repo on contribution site

### ISSUE THREAD

**Issue by Paalar** [dotkom/onlineweb-frontend#143]
When hovering over a repo on the contribution site the type will be basically unreadable. 

<img width="547" alt="screenshot 2018-11-24 at 13 19 02" src="https://user-images.githubusercontent.com/22390745/48968179-b5b9b600-efeb-11e8-982e-06e27ed335fe.png">

Two suggestions to solve it
1. Give it a background so it can be readable, maybe the same as the card itself so it looks like it extends the card
2. Add more height to the card so it will always be inside of it

Something extra:
Maybe change the black color when hovering to match the color of what you're hovering over.

**Comment by oleast** [comment]
I see we have to test in a few more browsers than we are currently testing in.
This works well in Chrome and Vivaldi, but not in Firefox and Edge. No idea about Safari, but I can't test that... 

How it currently looks in Blink based browsers:
![owf-contributions-hover](https://user-images.githubusercontent.com/14319313/48968577-ccfba200-eff1-11e8-8b3c-bd780f702099.png)

**Comment by mariush2** [comment]
This work on Chrome, Firefox and Safari now. Not sure about Edge. Closing this issue for now.
