### ISSUE TITLE
Add a PR (and maybe issue) template

### ISSUE THREAD

**Issue by plusk** [dotkom/onlineweb-frontend#145]
A `.github/` folder could contain a contributing note, issue, and PR template. See more info [here](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/). A PR template would be nice to remind people to add screenshots, which is nice in most changes, what with this being a frontend repo. 
Keep the template(s) simple. I think the ones we have for OW4 are way too bloated, and most of the time you just remove all of it and make your own. No need for checkboxes or handling the edge cases of all PRs. Just a nice simple "here's a description, here's the related issues it closes, here's the screenshots before and after (or just after)"

**Comment by sklirg** [comment]
(if you have admin settings to this repo) You can go here and generate some: https://github.com/dotkom/onlineweb-frontend/issues/templates/edit :)

**Comment by oleast** [comment]
We have this now #243
