### ISSUE TITLE
Should we maybe change the the information in career tab to list style?

### ISSUE THREAD

**Issue by kharann** [dotkom/onlineweb-frontend#147]
In the list view in the career tab i think we should have a list style for Type, Sted and Frist. Since when there's a lot of words, like "summerjob/internship" or bunch of location it will look a little weird. Maybe implement it in the standard view only or when the width is lower just like in the old OW4. 

Or maybe make the content of Type,sted,frist all start after the colon. 

Example image:
Left: Current look,     Right: What i think looks cleaner
![shrekcareerlist](https://user-images.githubusercontent.com/41551253/48969939-2241ae80-f006-11e8-9c2a-bcfb0b11feaa.png)

**Comment by henrikhorluck** [comment]
It would be very helpful if you labeled before/after on the pictures 🙂

**Comment by oleast** [comment]
This only appears as a problem if and only if the career opportunity has many locations.

In most other cases, I think it looks kinda strange to have it as a list style. It makes all of the cards a lot larger, while just adding whitespace to the right.
