### ISSUE TITLE
Require user login for certain parts of the application

### ISSUE THREAD

**Issue by torjusti** [dotkom/onlineweb-frontend#152]
Currently, no routes are hidden for guests, and you can therefore enter e.g. your profile statistics, which will simply show the loading spinner until you log in. I suggest we instead redirect the user to the login screen when they attempt entering these paths. Links such as the profile link in the header should also be hidden for guests.

**Comment by oleast** [comment]
I added the functionality to require login for specific routes, but it currently just renders a `401` with our 'balloon nyan cat'.

We currently don't have a specific login page, but we could implement something prettier than the current `401`. Something like a simple page which says you need to log in to view this page, with a logo (OWF logo?) and a big blue button to login in?
