### ISSUE TITLE
Shrink huge front page images

### ISSUE THREAD

**Issue by niklasmh** [dotkom/onlineweb-frontend#164]
I have a feeling that some images on the front page can grow too big on certain widths:
![image](https://user-images.githubusercontent.com/8504538/50991256-8962e600-1514-11e9-909b-f9a5ce0b9499.png)

It is possible to fix this setting a `max-height` and use `object-fit: cover` (or contain) on the img-tag to make the image scale in right proportions.

This results in (with `object-fit: cover`):
![image](https://user-images.githubusercontent.com/8504538/50991648-76044a80-1515-11e9-80ca-6635c2fb21a3.png)

Or `object-fit: contain`:
![image](https://user-images.githubusercontent.com/8504538/50991625-6127b700-1515-11e9-89ba-c35e5c612c2c.png)

**Comment by niklasmh** [comment]
The solution on this problem is transferable to #60.

**Comment by niklasmh** [comment]
@mariush2 Any status on this?

**Comment by mariush2** [comment]
I am doing a re-redesign of the frontpage views and detail views. So that will include a fix to this.

**Comment by mariush2** [comment]
This was confirmed as done with niklasmh.
