### ISSUE TITLE
Contact mail on events generated wrong when based on committee name 

### ISSUE THREAD

**Issue by chrlofs** [dotkom/onlineweb-frontend#172]
The contact email displayed on events can be generated wrong when using just the name of the committee managing the event. 

An example can be seen here:

<img width="350" alt="skjermbilde 2019-01-24 kl 23 30 26" src="https://user-images.githubusercontent.com/9264978/51712752-18e9b800-2030-11e9-8569-bb225eb0a9cb.png">

[https://beta.online.ntnu.no/events/660](https://beta.online.ntnu.no/events/660)

**Comment by henrikhorluck** [comment]
Genuine question: what should the email be in that case? There are several commitees were the contact mail isn't clear, perhaps we can add a `contact_email` to the group on OW4 (in some way or another)?

**Comment by oleast** [comment]
The real problem here resides in https://github.com/dotkom/onlineweb4/issues/1209

It is not currently possible to extend the built in Group model in Django.
The Django issue can be found here: https://code.djangoproject.com/ticket/29748

**Comment by oleast** [comment]
Using the email from the [Online Group](https://online.ntnu.no/api/v1/group/online-groups/) can now mitigate this
