### ISSUE TITLE
[module] Create pages for company information

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb-frontend#194]
Should have a page or pages to show off information about companies.

Something similar to the current implementation in [OW4]( https://online.ntnu.no/company/2/), but with a bit more useful information.

Could have things like:
- Past/future events
- Active career opportunities
- Information text about the company
- Contact information and link to website
- How many years they have worked with Online
- Previous names?

Could reuse components from events and career for related features.

**Comment by oleast** [comment]
Should also have more clear links to companies in the event view, pointing the user to information about the company

Should probably also be support for videos to showcase the company

**Comment by henrikhorluck** [comment]
Ref: since how long they have worked with Online, are you thinking we get this information from the oldest event/careeroppurtunity they have, or when they were added to the backend?

**Comment by oleast** [comment]
When they were added would be the easiest to do, and works well enough.

**Comment by henrikhorluck** [comment]
Wouldn't stuff like Gold Sponsor for "fadderuka" 2018, coffeesponsor and so on be stuff we should have on the company-pages as well?

**Comment by oleast** [comment]
Sound like great additions!

I would leave those things out of the initial implementation though.
I think we should get it working with current data first, and expand with more when we can.

**Comment by mariusaarsnes** [comment]
Actually getting some statistics can greatly help Bedkom! 

Everything shouldn't necessarily be visible for everyone but historic data can help the committee with improving events, helping companies improve etc. 

Getting an overview with historic data is something we are looking for in the long run with the new booking system (not part of the MVP).
