### ISSUE TITLE
Frontpage Image/CalendarView broken after going to article and back

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb-frontend#231]
So, another frontpage-event-bug!
Okay so this time I went to beta.onn, (I had the calendarview open from an earlier session) and I clicked on the "Fondstyret hjelper deg"-article, went back to beta.onn by clicking on the backbutton/swing on the touchpad, and the view was broken! I am using Chrome 73 on macOS, I was not logged in at the time.

![image](https://user-images.githubusercontent.com/36937807/56462933-9d4b9d00-63cb-11e9-9678-b28429140442.png)

**Comment by oleast** [comment]
This stems directly from ServiceWorker cache, and has been a problem before.

What happens is that the pre-rendered DOM from the server is stored in cache without knowledge of which event-view that was rendered/chosen. When the event view in cache is different from the one you load, react will basically get a 'merge conflict' of the event-view in cache, and the one react renders in the front-end based on your current cookies.

This is an example of the list view being stored in cache, while the chosen view in cookies is the image-view.

**Comment by henrikhorluck** [comment]
So is there any way to fix it?

**Comment by henrikhorluck** [comment]
And we have another one!
![image](https://user-images.githubusercontent.com/36937807/56510423-0b0ddb00-652a-11e9-8c9e-537beadc1b69.png)

**Comment by oleast** [comment]
That is the same thing, with different variables.

**Comment by mariush2** [comment]
What's the status on this?

**Comment by oleast** [comment]
I think this was solved by our move to Next?
