### ISSUE TITLE
Figure out how to handle the wiki

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb-frontend#255]
The wiki is a really important part of what we do and what we can offer.

We need a way for the wiki to be accessible when we make the move from OW4 to OWF.

There are multiple solutions to this problem:

The easiest would be to just add a rule and pass the wiki though via NGINX.
This would leave the wiki as it is right now, an is just kinda a way to push the problem into the future?

Another solution could be to implement a REST API for the wiki models.
This would let us implement a module for the wiki in OWF, or create a new front-end project for it. This could yield nice results, but will require some work.

Another solution would be to deploy another pre-packaged wiki, but that would be a lot of work, and does not seem feasible.

**Comment by aslakhol** [comment]
I like option 1. People are very accustomed to wikis being information first, design second. I don't think we really need to do anything for the wiki. (Other than information restructuring which I think seniorkom is working on).

**Comment by CarlOfHoly** [comment]
We have created a wiki project. For now it is solved by rerouting from OWF -> OW4
