### ISSUE TITLE
Sort opportunities with featured appearing first

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb-frontend#257]
**Describe the solution you'd like**
Career opportunities should be sorted to make featured ones appear on top.
They have the `featured` flag set in the model.

**Describe alternatives you've considered**
Featured opportunities should probably also add some context to why they are sorted to the top.
We could do this by adding an icon and some text to the card.
Something like a flag or a star below the image. Golden/yellow/orange text saying 'Fremhevet jobbmulighet' or something.

**Additional context**
They have the `featured` flag set in the model.

**Comment by henrikhorluck** [comment]
Was this fixed by #299 ? Or do we still need a sorting function that isn't based on id?

**Comment by oleast** [comment]
> Was this fixed by #299 ? Or do we still need a sorting function that isn't based on id?

This was halfway fixed, but we still need to ensure the ordering in the front-end.
Right now the ordering is as it should be because they come [ordered correctly from the API](https://github.com/dotkom/onlineweb4/blob/fe352b246ef10a7e64a41ccb31b790673b4c1819/apps/careeropportunity/views.py#L32-L36)

To ensure this ordering is consistent for all future use I think we should sort them in the front-end.
