### ISSUE TITLE
Fix sorting across browsers

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb-frontend#267]
Currently the sorting for career-oppurtunities, items in the shop in the profile-statistics, and probably more are sorted differently in Safari in comparision to Firefox and Chrome (and probably more), and should be fixed. This can be as easy as just use a `.sort()` in the relevant places, so it doesn't use the default sorting.

The sorting for career-oppurtunities should be fixed in this, if not before: https://github.com/dotkom/onlineweb-frontend/issues/257

**Comment by oleast** [comment]
This is addressed for the most part in the migration to Redux Toolkit, as sorting is part of the enity state
