### ISSUE TITLE
Finish Frontpage view for Offline

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb-frontend#27]
The frontpage view for Offline issues needs to be completed.

Basic functionality is completed, with a few bugs.
It currently only displays the first 10 elements (first page), while the rest are actually fetched. This is probably because of the functionality designed to keep you from going past the last issue of the last page.

Styling for the buttons to slide forward and backward need to be completed.

Styling animation for _sliding_ the issues left and right needs to be fixed as well

**Comment by henrikhorluck** [comment]
Can we make so it displays fewer Offline-covers depending on the width of the browser?

**Comment by torjusti** [comment]
Agreed, that's definitely something which needs to be done.

**Comment by oleast** [comment]
Resolved by #198
