### ISSUE TITLE
Markdown in article ingress doesn't work

### ISSUE THREAD

**Issue by plusk** [dotkom/onlineweb-frontend#274]
**Describe the bug**
Markdown isn't rendered in frontpage article ingress

**To Reproduce**
1. Go to frontpage
2. Scroll down to article section
3. See 

**Expected behavior**
Either not allow markdown in ingress, or render markdown in ingress preview. Since markdown works inside actual articles, we should just have the frontpage follow suit. 

**Screenshots**
![2019-06-14-11:27:37](https://user-images.githubusercontent.com/14059677/59499278-5a6fe800-8e97-11e9-9cae-56ecbe6667e8.png)

**Desktop:**
 - OS: Arch Linux with i3
 - Browser: Chromium 
 - Version: Version 75.0.3770.80 (Official Build) Arch Linux (64-bit)

**Comment by henrikhorluck** [comment]
#222 fixes this
