### ISSUE TITLE
Hovedsamarbeidspartnerlabel in the footer

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb-frontend#276]
**Is your feature request related to a problem? Please describe.**
I showed the new footer to my father and he said it looked like we worked for Knowit. 

**Describe the solution you'd like**
We should include the line "Hovedsamarbeidspartner" which we already have on the old website. 

**Describe alternatives you've considered**
Not doing this is also an option, I'm open to discussion.

**Comment by mariush2** [comment]
+1 on adding a text. Showed it to my mother and she did not see the connection
