### ISSUE TITLE
Add page to view an article

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb-frontend#28]
Articles need their own view to you can read them.

**Comment by henrikhorluck** [comment]
When implementing the comment section we should think wether we should 1. remove it altogether og 2. use something more light-weight, like https://victorzhou.com/blog/replacing-disqus/

**Comment by oleast** [comment]
I would say it can easily be ignored for the first basic implementation.

Comments are nice to have though, but I think it would be better to just implement a basic comment system for ourselves. Would be less of a barrier for our users to actually comment on things.

It's possible to just create an issue for it.
