### ISSUE TITLE
Fix naming of committees on event pages

### ISSUE THREAD

**Issue by mariusaarsnes** [dotkom/onlineweb-frontend#283]
**Describe the bug**
The naming of the responsible committee for an event is wrong.

**To Reproduce**
1. Go to an arbitrary event
3. Scroll down to see who is responsible for the event
4. See that the name is wrong.

**Additional context**
Committee names should start with a capital letter and not contain a capital "k". The spelling used is the old way of spelling committee names.

**Comment by oleast** [comment]
We recently created expanded group models which allow for the correct naming of committees: `https://online.ntnu.no/api/v1/group/online-groups/`
