### ISSUE TITLE
The calendar view of events does not display all events in that month

### ISSUE THREAD

**Issue by Paalar** [dotkom/onlineweb-frontend#305]
When selecting the third view for events (calendar) it will not display any of the events that happen on the last day of the month.

In the image linked, there are no events on October 31st, when there should be 3 events.
<img width="805" alt="Screenshot 2019-10-04 at 13 30 42" src="https://user-images.githubusercontent.com/22390745/66204606-819f2f00-e6ab-11e9-83b0-6954a50f1156.png">

If you select the second view for events (list) and go back to the calendar view it will display those 3 events as well.
<img width="843" alt="Screenshot 2019-10-04 at 13 30 55" src="https://user-images.githubusercontent.com/22390745/66204720-c3c87080-e6ab-11e9-99e9-65518725bd0f.png">

I am not sure if this only happens for the last day of the month.

Link to video https://streamable.com/epgab

**Comment by oleast** [comment]
I'm guessing this comes from the API request requesting events until and not including the last day of the month.
The events will appear after they are loaded into the EventsRepo (store-ish) by another API request. Displaying the actual events is a front end filter from the EventsRepo
