### ISSUE TITLE
Automatically check onlineweb4 user login state

### ISSUE THREAD

**Issue by Aborysa** [dotkom/onlineweb-frontend#317]
**Is your feature request related to a problem? Please describe.**
Right now you need to explicitly click on login every time the access token expires. 

**Describe the solution you'd like**
The app should check if the user is logged in to onlineweb4 and if the user is, automatically fetch an access token. This makes it so the only time the login button is ever present is when you're actually not logged in to the system at all.

**Comment by oleast** [comment]
Closed by #436
