### ISSUE TITLE
Event DetailView doesn't show markdown in the same way as OW4

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb-frontend#320]
**Describe the bug**
Look at https://beta.online.ntnu.no/events/785, as you can see, there is multiple places with `######a new sentence`, when that should be rendered as a `<h6/>`-tag
Example on OW4 https://online.ntnu.no/events/785/tdc-aspire-2019/

**Additional context**
This has also been a problem with articles, but was solved by using a regex-replace, that ensured there was a space between the last `#` and the start of the next sentence. While we could use that here, at this point it would probably be better to look into if we can config `<Markdown/>` to parse the markdown as wanted

**Comment by oleast** [comment]
This problem is solved by just writing markdown correctly.
We should not have to fix the code because of wrong markdown.

**Comment by henrikhorluck** [comment]
But is _is_ correct when looking at OW4, and I think is a dumb breaking change, since we need to change many earlier versions  of articles and events

**Comment by FluidSense** [comment]
I think I agree with @oleast on this one.
Although OW4 has been forgiving so far, OWF does not need to allow wrong markdown. 
People will learn, people will fix, and if people view earlier versions, it's not that big of an issue if they look a little weird.
I'm inclined to close this issue as a `wontfix` unless there are any more arguments as to why we should allow wrongly-written markdown.

**Comment by FluidSense** [comment]
I will close this issue, feel free to reopen if there are more arguments or multiple users asking for the feature!
