### ISSUE TITLE
HSP logo is green on hover

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb-frontend#347]
**Describe the bug**

**To Reproduce**
1. Go to any page
2. Scroll to footer
3. Hover on HSP logo
4. See color representing wrong company

**Expected behavior**
I expect to see a color representing the current HSP

**Screenshots**
![Peek 2020-04-18 10-21](https://user-images.githubusercontent.com/14319313/79632248-7a7ad280-815e-11ea-85f3-c17b2093b827.gif)

**Additional context**
I don't know what will be the right color :shrug:

**Comment by FluidSense** [comment]
Sure this is a bug and not a feature? 🤔 
For all we know, Bekk could be planning to merge with Knowit, to become Beknowit and thus have those colors!
On the serious side, I guess this is some styling which could be either removed or just changed to darker gray/black.
