### ISSUE TITLE
/events might display empty although there are events

### ISSUE THREAD

**Issue by FluidSense** [dotkom/onlineweb-frontend#363]
**Describe the bug**  

On direct access of events, the page is blank. However, there is still events in the Redux store.
I suspect this is due to the change of events in #348, where Debounced event list was tried implemented with Redux, but mostly left as is. On direct access, `filtered` is `true`, using the debounced list.
 
**To Reproduce**
1. Go to 'https://beta.online.ntnu.no/events' directly without accessing the frontpage
2. See the lack of events
3. Check Redux-store and see the events available for display

**Expected behavior**

A list of events should be rendered.

**Screenshots**

![](https://folk.ntnu.no/johannkv/img/hWAimqnUdh.png)
![](https://folk.ntnu.no/johannkv/img/33CJ2JmC9R.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox 
 - Version [e.g. 22] 75

**Additional context**

A quick fix is to remove the debounced list and purely use store, but that might disable the search.

**Comment by oleast** [comment]
This will be fixed by #358 

I'm just hesitating a bit on it because I think getting infinite scrolling can be a bit hard
