### ISSUE TITLE
Add capability to attend an event

### ISSUE THREAD

**Issue by oleast** [dotkom/onlineweb-frontend#39]
**This may require changes in the back-end**

Users should be able to attend an event from the Event Detail View.

Attending an event should display a modal which asks you to verify yourself.
This should probably be done with Google Recaptcha (v2 or v3).

For convenience, the modal should close automatically after the user is verified.

 - [x] Captcha #205  
 - [x] Påmeldingsknapp  #352   
 - [x] Påmeldingsmodal  #352  
 - [x] API-kall for å registrere påmeldingen #351     
 - [x] Avmeldingsknapp  
 - [x] Påmeldingslister  
 - [x] Betalingsredirect

**Comment by FluidSense** [comment]
Connected to #205

**Comment by Paalar** [comment]
I believe this is issue is solved by #386  and #480 ?
