### ISSUE TITLE
"Welcome to new onlineweb" message has a broken link to the github repository

### ISSUE THREAD

**Issue by petterroea** [dotkom/onlineweb-frontend#393]
**Describe the bug**  

When visiting the new onlineweb page, a message is displayed in the bottom left:

![Screenshot_2020-09-11_22-48-08](https://user-images.githubusercontent.com/725557/92971536-ed277a00-f480-11ea-8ec8-6e20f30e657d.png)

The github link in this message points to `https://github.com/dotkom/onlinewb-frontend`, which is incorrect

**To Reproduce**
1. Go to https://online.ntnu.no/
2. Observe the "welcome to new onlineweb" message
3. Click the github link
4. Observe 404 octocat

**Expected behavior**

I expect to visit the github repository i am writing this issue on

**Screenshots**

See above

**Desktop (please complete the following information):**
 - OS: `x86_64 Linux 5.8.7-arch1-1`
 - Browser: Firefox
 - Version: `80.0.1 (64-bit)`

**Comment by FluidSense** [comment]
Closed by #395
