### ISSUE TITLE
The "wow new website go report an issue" link has a typo

### ISSUE THREAD

**Issue by plusk** [dotkom/onlineweb-frontend#408]
https://github.com/dotkom/onlinewb-frontend != https://github.com/dotkom/onlineweb-frontend

**Comment by FluidSense** [comment]
I think this was resolved by #395, have you tried a hard-reload / empty cache?

**Comment by S1GGEN** [comment]
Duplicate with #393

**Comment by oleast** [comment]
> I think this was resolved by #395, have you tried a hard-reload / empty cache?

Seems that there are a lot of problems with the cache persisting like this even if it shouldn't?
Could be a thing to look into
