### ISSUE TITLE
Handle Next-warnings

### ISSUE THREAD

**Issue by FluidSense** [dotkom/onlineweb-frontend#412]
Currently, we are prompted with 3 warnings on setup.

~~1. FrontPage returned an empty object from `getInitialProps`. This de-optimizes and prevents automatic static optimization. https://err.sh/vercel/next.js/empty-object-getInitialProps~~
2. Please do not use `@import` CSS syntax in createGlobalStyle at this time, as the CSSOM APIs we use in production do not handle it well. Instead, we recommend using a library such as react-helmet to inject a typical <link> meta tag to the stylesheet, or simply embedding it manually in your index.html <head> section for a simpler app.
3. Warning: viewport meta tags should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-viewport-meta

**Comment by FluidSense** [comment]
Number 2 could originate from[ '@dotkomonline/design-system'](https://github.com/dotkom/design-system/issues/184)

**Comment by aslakhol** [comment]
2 is resolved by #502 and dotkom/design-system#190 

3. is resolved by #502

**Comment by aslakhol** [comment]
1. is moved to #503

**Comment by FluidSense** [comment]
Resolved in favor of #503
