### ISSUE TITLE
Reverse the list of events in the middle tab on the landingpage

### ISSUE THREAD

**Issue by Westermoen** [dotkom/onlineweb-frontend#427]
The list of events shown in the 2nd/middle tab on the landingpage displays the events in the wrong order as shown in the image below.
The list should be reversed so the event occuring closest to the present day is shown on top.

<img width="1132" alt="Skjermbilde 2020-09-16 kl  10 18 04" src="https://user-images.githubusercontent.com/15379479/93311156-ec3a7380-f805-11ea-8dc6-77434cc9350f.png">

**Comment by FluidSense** [comment]
Reversing this view without any further changes will also reverse the view in /events, resulting in wrong ordering on infinite scroll-loading. The sort order could probably be decided by a prop so the views can sort differently.

**Comment by FluidSense** [comment]
The events are also sorted in the Redux-store, and as such require a manual sort after retrieving the events from the store.
