### ISSUE TITLE
OW logs me out when closing and reopening a tab.

### ISSUE THREAD

**Issue by PeterRydberg** [dotkom/onlineweb-frontend#430]
**Describe the bug**  
OW has a tendency to log me out very often (at least in the visual sense, I have to click "Logg inn" every time I open a new tab). I assume this is not intended behaviour.

**To Reproduce**
1. Log into OW.
2. Open a new tab.
3. See that I am logged out in the new tab.

**Expected behavior**
Stay logged in as long as the session is unexpired.

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 85.0.4183.102 (Official Build) (64-bit)

**Comment by FluidSense** [comment]
Closed in favor of #317
