### ISSUE TITLE
Display price on eventpage

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb-frontend#431]
**Is your feature request related to a problem? Please describe.**
When signing up for an event I should be able to see the price before I go to pay for the event. Hiding the price before you go into the payment is bad enough, but if you are considering signing up for a paid event after the unattend deadline is out you can't see the price. 

There actually is no way to tell that an event costs money unless it says so in the supplied text.

**Comment by tokongs** [comment]
This is fixed by #444
