### ISSUE TITLE
Unattend from waiting list sends unattend email to commitee

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb-frontend#433]
**Describe the bug**  
We have one report of this case, it should be tested before we are sure that this is what is happening. 

A person who is on the waiting list should be able to unattend even after the deadline. This currently works as intended, but when that person signs out the committee in question gets an email announcing that the person has been unattended. This email was created to let people know when people were unattended through the dashboard. 

**To Reproduce**
1. Sign up to an event that is full. (and registration deadline is not passed)
2. Wait until unattend deadline is passed
3. Unattend from the waiting list
4. Ask the committee if they got a warning email. 

**Expected behavior**
A person on the waiting list should be able to remove themselves from the waiting list, even if the unattend deadline is passed, and this should not send a warning email to the arranging committee.

**Comment by FluidSense** [comment]
https://github.com/dotkom/onlineweb4/blob/4adbfe17c8cfa74da14062160c5a650bead16e4a/apps/events/models/Attendance.py
I suspect OW4 uses `delete` while the API uses `unattend`. Not sure if OWF should move to use `delete` or if `unattend` should check if the `user` and `admin_user` is the same before sending mail.

**Comment by aslakhol** [comment]
This will be resolved by https://github.com/dotkom/onlineweb4/pull/2531
