### ISSUE TITLE
Frontend does not display all changes to an event

### ISSUE THREAD

**Issue by erikskaar** [dotkom/onlineweb-frontend#434]
**Describe the bug**  
When you update an event that you have created earlier the information about the event seem to not update on the event page. Things such as the description, preamble and dates are not updated. The unregister from event date seems to be updated, but not the rest of the info. It will also not display on the frontpage of the website, unless you go from the event page by clicking show and then press the logo in the top left. It will then display with 0 participants until you refresh or navigate to another page. 

**To Reproduce**
1. Create event
2. Edit event later
3. See changes not applied

**Expected behavior**
The expected behavior is that the details will be updated on the event page and that the event will show on the frontpage.

**Screenshots**
![image](https://user-images.githubusercontent.com/43439578/93368571-73abd500-f84e-11ea-9ae6-3fce857b0013.png)

![image](https://user-images.githubusercontent.com/43439578/93368535-668ee600-f84e-11ea-8bf1-244fedc31cce.png)

**Desktop (please complete the following information):**
 - OS: Windows & Linux
 - Chrome
 - Version 85

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10
 - Browser Chrome
 - Version unsure

**Additional context**
Seems to be something to do with caching. It does show in the old OW just fine, but the link will not work if you just add "old." before the URL. I don't know if this is relevant.

**Comment by FluidSense** [comment]
I think this should be resolved by #493, could you confirm that this problem no longer exists @erikskaar ?

**Comment by FluidSense** [comment]
I will close this and assume it is solved as mentioned. Feel free to reopen or request reopening if it is still an issue
