### ISSUE TITLE
"Velkommen til nye Onlinewebben" always appearing and duplicating

### ISSUE THREAD

**Issue by Nicolaad** [dotkom/onlineweb-frontend#454]
**Describe the bug**  
The "Velkommen til nye Onlinewebben" popup is always appearing on entering the online web mainpage, Despite clicking "do not appear". In fact, it would duplicate when entering an article and going back to the main page. 

**To Reproduce**
1. Go to https://online.ntnu.no/
2. Check the "do not show this anymore" checkbox and close the popup
3. Click on any article
4. Scroll down to 'Click on the online logo'
5. See error 
(do only step 1, 3 and 4 and it will produce multiple at a time)

**Expected behavior**
No more "Heisann, velkommen til onlinvewebben popups"

**Screenshots**
https://imgur.com/a/GRrKMlD

**Desktop (please complete the following information):**
 - OS: [Ubuntu, Windows]
 - Browser [Firefox]
 - Version [78.0.2]

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung A70]
 - OS: [Android 10]
 - Browser [Firefox]
 - Version [81.1.1]

**Comment by FluidSense** [comment]
Resolved by #460
