### ISSUE TITLE
404 when accessing event through hyperlink

### ISSUE THREAD

**Issue by skanin** [dotkom/onlineweb-frontend#463]
**Describe the bug**  

Upon entering an event through hyperlink, a 404 error is shown (with the text "Dette arrangement er ikke tilgjengelig."). The event are comité-only (group restriction is set to "komitéer"). 

**To Reproduce**
1. Paste link to restricted event in browser
2. Press enter
3. See error page

**Expected behavior**

The event should show, if user is logged in and are member of a comité

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.14.81

**Comment by oleast** [comment]
I believe this is the same as #458 

The initial request is made before the user is authenticated in the background. Since the auth state doesn't trigger another fetch the event or whopping cart won't ever be loaded after the user logs in.
