### ISSUE TITLE
Cannot sign up to comité-only event

### ISSUE THREAD

**Issue by skanin** [dotkom/onlineweb-frontend#478]
**Describe the bug**  

Cannot sign up to comité-only event.

**To Reproduce**
1. Go to comité-only event
2. Click on 'meld meg på'
3. See that nothing happens

**Expected behavior**

Sign up should be available, as long as you are signed in and member of comité.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.0 Beta (20A5374i)
 - Browser Brave
 - Version 1.14.84

**Comment by FluidSense** [comment]
This was due to a change in OW4, affected all events and should now be resolved.
