### ISSUE TITLE
Cannot withdraw from comité-only event

### ISSUE THREAD

**Issue by skanin** [dotkom/onlineweb-frontend#479]
**Describe the bug**  

Cannot withdraw from comité-only event.

**To Reproduce**
1. Sign up to comité-only event
2. Try to withdraw
3. See that it is not working

**Expected behavior**

It should be possible to withdraw from comité-only event.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.0 Beta (20A5374i)
 - Browser Brave
 - Version 14.1.84

**Additional context**

Getting 403 error when trying to withdraw from event. Possibly related to #478

**Comment by FluidSense** [comment]
This was due to a change in OW4, affected all events and should be resolved.
