### ISSUE TITLE
Replace temporary Online-icons with official logo.

### ISSUE THREAD

**Issue by PeterRydberg** [dotkom/onlineweb-frontend#483]
**Describe the bug**  
Not much of a _bug_. The (very cool!) icons on OWF are wrong, and should be replaced by Online's official logo now that the new frontend is launched in production. This is to prevent wrong logo associations and confusion. Should fix itself by replacing the files in `public/img/icons/` ⚡.

**To Reproduce**
1. Look at favicon in the tab.
2. Look at the background on empty event images.
3. Possibly more places? May need some extra insight here.
4. These icons are not from the official Online logo.

**Expected behavior**
The redesigned logo should be used as standard where needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/22096301/94687177-2d657400-032c-11eb-8fb6-4a78914ac0b0.png)
![image](https://user-images.githubusercontent.com/22096301/94687187-32c2be80-032c-11eb-8b90-8153a45d070f.png)
etc.

**Comment by oleast** [comment]
R.I.P my logo 💀

**Comment by FluidSense** [comment]
@PeterRydberg I have read the "grafisk profil"-page, but I am still uncertain: Can we use the logo-icon with the current colors? The current colors makes it easy to discern the type of event when an image is not present

**Comment by FluidSense** [comment]
Also, @dotkomonline/design-system ships both the current logo and icon, and can be used instead

**Comment by PeterRydberg** [comment]
You may! I might clarify that page a bit, but seeing as it has a practical purpose, changing the colors for _icon_ use rather than _logo_ use it should be permitted.

**Comment by Paalar** [comment]
I believe #487 solves this issue.
