### ISSUE TITLE
The apply now button on the career page should go to a mailto link if there is no application link. 

### ISSUE THREAD

**Issue by aslakhol** [dotkom/onlineweb-frontend#489]
**Is your feature request related to a problem? Please describe.**
Some career opportunities don't have an application link. Per #484 we hide the button when we don't have the link. Bedkom mentioned that they thought it would be a good idea to be able to put an application email in the button, and I agree. 

**Describe the solution you'd like**
I think the cleanest solution would be to have a new field in the dashboard for an application email and to use that if application link is not available. 

**Describe alternatives you've considered**
We could make sure that the applicationLink property always either has a link to an application page, or to a mailto. But I think that would be messy.

**Comment by aslakhol** [comment]
https://github.com/dotkom/onlineweb4/issues/2544

**Comment by FluidSense** [comment]
Closed by #496
