### ISSUE TITLE
Separate waiting list people on the attendees viewer.

### ISSUE THREAD

**Issue by PeterRydberg** [dotkom/onlineweb-frontend#508]
**Is your feature request related to a problem? Please describe.**
When viewing attendees on an event, everyone including people on the waiting list are displayed (as anonymous). This gives the impression that more than the maximum amount of people are attending the event, which is only fun if you like grinding on sweaty people in a cramped room. It's unclear whether this is a bug or a feature, but because you guys are god-like programmers who can do no wrong, I'm assuming it's just an underdeveloped feature.

For instance, on the Oktoberfest-event, some first grader anon is on place 61 (see image), even though the event only accepts 60 people. This salamander should check itself before it metaphorically wrecks itself.

**Describe the solution you'd like.**
I propose separating the would-be attendees on the waiting list and the people that _will_ be attending the event when viewing the attendees list. This separation could be either a thin line, a list break, or the words "På venteliste". Truly visionary.

**Describe alternatives you've considered.**
You could also just remove the waiting list people from the attendees-viewer, but that's not as fun.

**Additional context.**
![image](https://user-images.githubusercontent.com/22096301/95976489-dfff0180-0e17-11eb-9c5f-9db634f93ba6.png)

**Comment by FluidSense** [comment]
This is a problem with our data: https://github.com/dotkom/onlineweb4/issues/2551

**Comment by PeterRydberg** [comment]
Do you think it's a nice feature to have? It's not an entirely bad idea to be able to opt into showing yourself on a waiting list and seeing how far along your friends have come.
