### ISSUE TITLE
Exporting events as .ics file

### ISSUE THREAD

**Issue by Xtrah** [dotkom/onlineweb-frontend#516]
**Is your feature request related to a problem? Please describe.**
Old onlineweb had the possibility to export/subscribe to events.ics (calendar file with all events), while the new one does not
https://old.online.ntnu.no/events/events.ics

**Describe the solution you'd like**

The same in new onlineweb

**Describe alternatives you've considered**

**Additional context**

![old onlinweb](https://i.imgur.com/x9I6MqV.png)

**Comment by Xtrah** [comment]
This doesn't really solve the issue. Old OW provided a calendar URL for *all* events my user is signed up for, so it was simply subscribing to that one URL.

**Comment by henrikskog** [comment]
Agreed, I mixed up the PR's. Should be closed by https://github.com/dotkom/onlineweb-frontend/pull/682. See https://online.ntnu.no/profile/settings/calendar
