### ISSUE TITLE
Only "sosialt" events appear initialy in the rightmost event column

### ISSUE THREAD

**Issue by Nicolaad** [dotkom/onlineweb-frontend#528]
**Describe the bug**  
When you enter the webpage, only events marked as "sosialt" (the green ones) appear in the right column, preventing events with categories such as "Annet" and "Realfagskjelleren" from appearing.

If you click the list or calendar view, and then go back to the 3 column event view, then the other events will be shown properly.

**To Reproduce**
1. Go to 'https://online.ntnu.no/'
2. See lack of events not marked as "Bedriftspresentasjon", "kurs" and "sosialt" (this is the bug)
3. Click on the calender view for Arrangementer
4. Click on the column view for Arrangementer
5. Observe that events with other categories than "sosialt" now appears in the right column (which is what is expected at step 2) (NB! this requires events with other categories to exist)

**Expected behavior**
Events of diffrent categories such as "annet" and "realfagskjelleren" appears initially in the right column together with "sosialt" events.

**Screenshots**
[https://imgur.com/a/yk8wpZE](https://imgur.com/a/yk8wpZE)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 81.0.2 (64-bits)

**Comment by Nicolaad** [comment]
This seems to still be an issue, and events of the type of "Realfagskjelleren" is currently hidden  unless the user jumps from calender and back to column view :\

**Comment by HenrikSkog** [comment]
This is still an issue. Not quite sure if it is the same, but the events shown in "social" differ betweeen initial page load and if you go to cal- or row mode and back
