### ISSUE TITLE
Fakturainfo in the footer is wrong

### ISSUE THREAD

**Issue by kharann** [dotkom/onlineweb-frontend#569]
**Describe the bug**  

Information is currently: 
![image](https://user-images.githubusercontent.com/41551253/134359051-7b2e2291-35c5-41d7-8256-4e045c16eecc.png)

**Expected behavior**
Should be 

Online Linjeforening
Sem Sælands v. 9 / Sem Sælands vei 9
7491 Trondheim

**Comment by anderssonw** [comment]
Should be 

Online Linjeforening
Sem Sælands v. 9
7491 Trondheim

OR

Online Linjeforening
Sem Sælands vei 9
7491 Trondheim

:)
