### ISSUE TITLE
Filter out "empty" users from user search page

### ISSUE THREAD

**Issue by tokongs** [dotkom/onlineweb-frontend#572]
The user search page contains users which i assume have been anonymized. This look sTuPiD. We should filter them out.

[https://online.ntnu.no/profile/search](https://online.ntnu.no/profile/search)

![profile_search](https://user-images.githubusercontent.com/6499473/135751651-09f32a75-9a7c-405e-894b-dc47d1ac808c.png)

**Comment by henrikskog** [comment]
Denne siden er tatt bort
