### ISSUE TITLE
Fix display of event image view on smaller screens

### ISSUE THREAD

**Issue by blauks** [dotkom/onlineweb-frontend#60]
If you look at the image view of the events on a smaller screen the three big event viewers (that are supposed to group the different events) are shown on top, followed by the 9 other events (that are supposed to be split up into the different groups). I think the best way to present the image view is to first have one of the big event viewers, and then have the 3 corresponding smaller ones that are in the same group. And then the same for the 2 others.

**Comment by mariush2** [comment]
This was done in #213, closing.
