### ISSUE TITLE
Improve focus outlines

### ISSUE THREAD

**Issue by sardred** [dotkom/onlineweb-frontend#96]
Like @oleast mentioned in #90, the focus outline is maybe not ideal.

Possible solutions
>Could this be what we need? [W3C :focus-visible selector](https://drafts.csswg.org/selectors-4/#the-focus-visible-pseudo)

>There is a polyfill for it https://github.com/wicg/focus-visible

**Comment by oleast** [comment]
This should be fixed now via #187
